### ISSUE TITLE
Still alive ? :D

### ISSUE THREAD

**Issue by Thovi98** [YunoHost-Apps/streama_ynh#5]
Je viens de découvrir StreamaServer, et ça m’intéresse fortement !!
Sera-t-il bientôt porté sur Yunohost ? J’en serais fortement reconnaissant ! 

Je n’ai aucune notion de développement malheureusement, mais si je peux aider pour traduire ou quoi (anglais-français) je pourrais faire mon possible (plutôt anglais --> français que l’inverse, je ne suis pas parfait bilingue).

Merci d’avance !

**Comment by Thovi98** [comment]
I tried to install streama_ynh on Yunohost after installing Yunohost on Virtualbox, but my pc is not powerful enough to run Virtualbox... Any idea how I can help testing ?

**Comment by Thovi98** [comment]
> I tried to install streama_ynh on Yunohost after installing Yunohost on Virtualbox, but my pc is not powerful enough to run Virtualbox... Any idea how I can help testing ?

I did it ! I could install Virtualbox and test the package, I will put my issues.

**Comment by liberodark** [comment]
yes im a live
