### ISSUE TITLE
Install only on /

### ISSUE THREAD

**Issue by Thovi98** [YunoHost-Apps/streama_ynh#6]
The package can only be installed on domain.tld/ and not any other directory like domain.tld/streama.

Is it possible to remedy this problem ?

**Comment by liberodark** [comment]
Probably need to see that

**Comment by Thovi98** [comment]
To be more precise, when I try to install it on domain.tld/streama, I receive a 502 bad gateway response. I don’t know if that helps you.

**Comment by Thovi98** [comment]
May be related to https://github.com/streamaserver/streama/issues/703 ?

**Comment by liberodark** [comment]
Ok im going to try too

**Comment by liberodark** [comment]
https://github.com/streamaserver/streama/issues/703#issuecomment-573278644
