### ISSUE TITLE
App set as "notworking"

### ISSUE THREAD

**Issue by Thovi98** [YunoHost-Apps/streama_ynh#8]
Why is the app set as notworking on https://yunohost.org/#/apps_fr ?

It works pretty wel despite some bugs. Installation goes well.

**Comment by liberodark** [comment]
This app work

**Comment by Thovi98** [comment]
It would then be nice to update apps.json I think : https://github.com/YunoHost/apps/blob/master/apps.json#L2593
So people will worry less, and it will be available to download directly in the community list if I understand well !
