### ISSUE TITLE
Update to Streama v1.9.1

### ISSUE THREAD

**Issue by Thovi98** [YunoHost-Apps/streama_ynh#9]
New version has been released : https://github.com/streamaserver/streama/releases/tag/v1.9.1

Would it be possible to implement it ? Thanks.

Since Streama v1.8.1, java 11 is compatible. Maybe update openjdk-8-jre-headless to openjdk-11-jre-headless ?

**Comment by liberodark** [comment]
ok im going to try

**Comment by Thovi98** [comment]
Thanks for the update ! But I cannot do it : 
https://paste.yunohost.org/raw/kifabuzadi

I don’t know if it’s related with te issue, but when my Yunohost says me I can upgrade, it says that I can upgrade to 1.8.0 

![screenshot 3](https://user-images.githubusercontent.com/51749973/83259051-ab1b4680-a1b7-11ea-8dcd-eb945e140814.jpg)
